# Generated by Django 4.1.4 on 2022-12-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staf_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
