# Generated by Django 4.1.4 on 2022-12-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_m_s', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staf_user',
            name='password',
            field=models.IntegerField(default=4939),
            preserve_default=False,
        ),
    ]
