# Generated by Django 4.1.4 on 2022-12-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_m_s', '0002_staf_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('auth', models.TextField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
