# Generated by Django 4.1.4 on 2022-12-29 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_m_s', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('mname', models.TextField()),
                ('lname', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_m_s.books')),
            ],
        ),
    ]
