# Generated by Django 4.1.4 on 2022-12-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_m_s', '0005_alter_student_address_alter_student_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='books',
        ),
        migrations.AddField(
            model_name='student',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='library_m_s.books'),
        ),
        migrations.AddField(
            model_name='student',
            name='book_i',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
