# Generated by Django 4.1.4 on 2022-12-31 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_m_s', '0007_remove_student_book_i_alter_books_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='book',
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='narrow_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='library_m_s.books')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='library_m_s.student')),
            ],
        ),
    ]
