# Generated by Django 4.1.4 on 2023-01-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_m_s', '0008_remove_student_book_remove_student_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
